# Generated by Django 5.0.1 on 2024-01-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='News Title')),
                ('ndetail', models.TextField(max_length=1000, verbose_name='News Detail')),
                ('nimg', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Match name')),
                ('cat', models.IntegerField(choices=[(1, 'T20'), (2, 'ODI'), (3, 'Test')], verbose_name='Category')),
                ('status', models.CharField(max_length=300, verbose_name='match status')),
                ('team1_name', models.CharField(max_length=50, verbose_name='team1 name')),
                ('team2_name', models.CharField(max_length=50, verbose_name='team2 name')),
                ('team1_score', models.CharField(max_length=50, verbose_name='team1 score')),
                ('team2_score', models.CharField(max_length=50, verbose_name='team2 score')),
                ('is_active', models.BooleanField(default=True)),
                ('team1_flag', models.ImageField(upload_to='image')),
                ('team2_flag', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50, verbose_name='Team Name')),
                ('timage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Matches2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium', models.CharField(max_length=300, verbose_name='match stadium')),
                ('m_date', models.DateField()),
                ('m_price', models.FloatField()),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='cricketapp.matches')),
            ],
        ),
        migrations.CreateModel(
            name='BookTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(default='Wing A', max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=0)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='cricketapp.matches')),
                ('mid1', models.ForeignKey(db_column='mid1', on_delete=django.db.models.deletion.CASCADE, to='cricketapp.matches2')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='Player Name')),
                ('jersey_no', models.IntegerField()),
                ('cat', models.IntegerField(choices=[(1, 'India'), (2, 'Australia'), (3, 'Pakistan'), (4, 'England'), (5, 'Afghanistan'), (6, 'Sri Lanka'), (7, 'Bangladesh'), (8, 'South Africa'), (9, 'West Indies'), (10, 'New Zealand')], verbose_name='Category')),
                ('pimg', models.ImageField(upload_to='image')),
                ('ptype', models.CharField(max_length=50)),
                ('tid', models.ForeignKey(db_column='tid', on_delete=django.db.models.deletion.CASCADE, to='cricketapp.teams')),
            ],
        ),
    ]
