# Generated by Django 5.0.1 on 2024-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Match name'),
        ),
    ]
