# Generated by Django 5.0.1 on 2024-01-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0002_alter_matches_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='cat',
            field=models.IntegerField(choices=[(1, 'International Teams'), (2, 'League Teams')], default=0, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
