# Generated by Django 5.0.1 on 2024-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0003_teams_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='cat',
            field=models.IntegerField(choices=[(1, 'India'), (2, 'Australia'), (3, 'Pakistan'), (4, 'England'), (5, 'Afghanistan'), (6, 'Sri Lanka'), (7, 'Bangladesh'), (8, 'South Africa'), (9, 'West Indies'), (10, 'New Zealand'), (11, 'Chennai Super Kings'), (12, 'Mumbai Indians'), (13, 'Gujrat Titans'), (14, 'Lucknow Super Giants'), (15, 'Royal Challenger Bangalore'), (16, 'Sunrisers Hyderabad'), (17, 'Kolkata Knight Riders'), (18, 'Delhi Capitals'), (19, 'Punjab Kings'), (20, 'Rajasthan Royals')], verbose_name='Category'),
        ),
    ]
