# Generated by Django 5.0.1 on 2024-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0004_alter_players_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktickets',
            name='amount',
            field=models.IntegerField(default=800),
        ),
    ]
