# Generated by Django 5.0 on 2024-02-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
